development:
  adapter: postgresql
  encoding: unicode
  database: teachers_students_development
  pool: 2
  username: sholom
  password: test

production:
  adapter: postgresql
  encoding: unicode
  database: teachers_students_development
  pool: 2
  username: sholom
  password: deleteme
